version: '3.8'

services:
  pester-server:
    build:
      context: ./pester_server
      dockerfile: Dockerfile
    container_name: pester-server
    ports:
      - "4000:4000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=4000
